#!/usr/bin/env bash
# TFWWW

if [[ $# -eq 2 ]]; then
    domain="$2.$1"
else
    domain="www.$1 lb-01.$1 web-01.$1 web-02.$1"
fi

dig $domain | awk '/ANSWER SECTION:/{getline; split($0,a,"."); print "The subdomain", a[1], "is a", $4, "record and points to", $5}'
