#!/usr/bin/env bash
# Run Nginx as Nginx and 7 lines or less
chown nginx /etc/nginx/nginx.conf
chmod 700 /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo -u nginx bash -c 'service nginx start'
