#!/bin/bash
#{Command} ssh - Is used to connect with the SSH remote client. Tells the system
#to establish a secure encrypted connection to the host machine.
#{Flag} -i [identity_file] - Selects a file from which the identity (private key)
#for public key authentication is read.
#{Arguments} [user_name@host(IP/Domain_name)]
#	username represents the account being accessed on the host.
#	host refers to the machine, which can be a computer or a router being accessed.
#	This can be an IP address (for example, 192.168.1.24) or a domain name
#	(for example, www.domainname.com).
ssh -i ~/.ssh/school ubuntu@34.74.181.130
